### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Aholicknight** [can1357/NoVmp#15]
I am sorry for this not being an issue. I have a question regarding NoVmp, I dumped the vmprotected DLL with Scylla and tried to use it with NoVmp, This shows up when I input the DLL:
![image](https://user-images.githubusercontent.com/7843719/94845267-b1773480-03dc-11eb-9b13-95a756068a46.png)

If I press any key the program closes. If anyone can help me that would be great, thank you.

**Comment by 0xGREG** [comment]
https://github.com/can1357/NoVmp#usage

**Comment by Aholicknight** [comment]
Thank you for this @0xGREG but I am wondering how to **input** the exe or the DLL into the program. Do I drag the file into the exe or do I use `NoVmp.exe <name of dll or exe here>`

**Comment by 0xGREG** [comment]
It's literally explained there dude...

**Comment by Aholicknight** [comment]
Okay thank you.
