### ISSUE TITLE
README mistake

### ISSUE THREAD

**Issue by UndefinedIdentifier** [can1357/NoVmp#18]
`README.md` usage about -base parameter 

> -base 0x14000000

It looks like we're missing a 0.

**Comment by can1357** [comment]
Not really a mistake given that it depends on the compiler settings, sometimes it's 0x180000000, sometimes it's 0x140000000, sometimes it's 0x1C0000000. This is not a fixed number people should copy paste but just a sample, but if you send a PR i'll merge it.
