### ISSUE TITLE
Error: Invalid VIP.

### ISSUE THREAD

**Issue by sverige-ko** [can1357/NoVmp#21]
What's the issue? What does invalid VIP mean?

`Discovered vmenter at 00007FF60245C2F0
Discovered vmenter at 00007FF60245CDB0
Lifting virtual-machine at 000000000008EBC1...
Error: Invalid VIP.
Lifting virtual-machine at 0000000000396A03...
Error: Invalid VIP.
Lifting virtual-machine at 000000000024A686...
Error: Invalid VIP.
Lifting virtual-machine at 00000000001ED7C2...
Error: Invalid VIP.
Lifting virtual-machine at 000000000038F7B1...
`

**Comment by can1357** [comment]
Please read.
