### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by oureveryday** [can1357/NoVmp#26]
I got compile error when compiling NoVMP. Tried to fix some, but some still error.
Maybe latest version VTIL-core cause this problem? Because the VTIL commit 98b44e3afa0a82e26f419b407d4c7a1c093f5e99 not exist. So I used latest version of VTIL and linux-pe.
I am using VS 2019 latest version and I made sure I am using latest /std:C++latest , but still get these error.
So can you solve these compile error, or tell something I need to do?
Thanks!

`Error C2641 Unable to deduce the template parameter of "std::lock_guard" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\main.cpp 249
Error C2440 "specialization": Cannot convert from "bool" to "vtil::optimizer::execution_order" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\demo_compiler.hpp 279
Error C2893 Failed to specialize function template "std::lock_guard<_Mutex> std::lock_guard(_Mutex &)" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\main.cpp 295
Error C2784 "std::lock_guard<_Mutex> std::lock_guard(std::lock_guard<_Mutex>)": Failed to derive template parameter NoVmp C:\Users\ from "void" to "std::lock_guard<_Mutex>" Username\Desktop\NoVMP\NoVmp\main.cpp 295
Error C2784 "std::lock_guard<_Mutex> std::lock_guard(std::lock_guard<_Mutex>)": Failed to derive template parameter NoVmp C:\Users\ from "void" to "std::lock_guard<_Mutex>" Username\Desktop\NoVMP\NoVmp\main.cpp 295
Error C2664 "char *strcpy(char *,const char *)": Cannot convert parameter 1 from "coff::scn_string_t" to "char *" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\main.cpp 366
Error C2664 "int memcmp(const void *,const void *,size_t)": Cannot convert parameter 2 from "coff::scn_string_t" to "const void *" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\ vmprotect\vtil_lifter.cpp 193
Error C2660 "vtil::optimizer::aux::analyze_branch": Function does not accept 4 parameters NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 500
Error C3536 "branch_info": Cannot use NoVmp before initialization C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 505
Error C2530 "branch": Must initialize reference NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 505
Error C3531 "branch": Symbols whose type contains "auto" must have initializer NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 505
Error C2143 Syntax error: Missing ";" (before ":") NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 505
Error C2143 Syntax error: missing ";" (before ")") NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 505
Error C2100 Illegal indirect addressing NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 513
Error C2672 "vtil::zip": No matching overload function was found NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 533
Error C2059 Syntax error: ":" NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 533
Error C2143 Syntax error: missing ";" (before "{") NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 534
Error C2065 "idx": Undeclared identifier NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 535
Error C2100 Illegal indirect addressing NoVmp C:\Users\Username\Desktop\NoVMP\NoVmp\vmprotect\vtil_lifter.cpp 536`

**Comment by can1357** [comment]
This repo is not ported to the latest version of VTIL, you can fix this issue by just using the version it is using in the first place. If you'd like to port, you will have to fix the errors which shouldn't be too hard.

**Comment by oureveryday** [comment]
Ok thanks I know
