### ISSUE TITLE
New issue while compiling on Linux

### ISSUE THREAD

**Issue by hyperchem** [can1357/NoVmp#4]
I installed lastest libc++-dev，switched compiler to clang 10, and fixed some issues in  Pull Requests. But I still get a compilation error like follow:

/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1756: undefined reference to `std::__throw_length_error(char const*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

anyone know how to fix this ?

**Comment by can1357** [comment]
Try with the latest commit, eitherway doesn't seem like a NoVmp issue since it comes from the STL.
