### ISSUE TITLE
Error: Invalid VIP

### ISSUE THREAD

**Issue by UndefinedIdentifier** [can1357/NoVmp#9]
I packed a 64-bit exe to test, but show message as below.
![image](https://user-images.githubusercontent.com/9676660/92598186-0db5cf80-f2db-11ea-992b-27d9ff54addf.png)
could you give me a target to test?thx

**Comment by can1357** [comment]
Did you pass the `-base` argument?

**Comment by UndefinedIdentifier** [comment]
yes.

**Comment by UndefinedIdentifier** [comment]
> Did you pass the `-base` argument?

yes, I passed `-base 0x7FF6AC910000` 
[Test.vmp_dump.exe.zip](https://github.com/can1357/NoVmp/files/5198952/Test.vmp_dump.exe.zip)

**Comment by can1357** [comment]
That's not the original base address, you need to pass the unpacked image's base address:
